name: Daily Extractor

on:
  schedule:
    - cron: '0 5 * * *'  # 07:00 Praha = 05:00 UTC
  workflow_dispatch:      # manuálne spustenie z GitHubu

jobs:
  run-extractor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: echo "No dependencies needed"

      - name: Run extractor
        run: python golemio_libraries.py

